# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000001)
$foreground = rgb(F4F2F3)
$color0 = rgb(000001)
$color1 = rgb(27292C)
$color2 = rgb(272A2D)
$color3 = rgb(2B2E31)
$color4 = rgb(676D6F)
$color5 = rgb(676D6F)
$color6 = rgb(A8A4A7)
$color7 = rgb(E7E5E6)
$color8 = rgb(A2A0A1)
$color9 = rgb(34373B)
$color10 = rgb(34373B)
$color11 = rgb(3A3E42)
$color12 = rgb(899194)
$color13 = rgb(899194)
$color14 = rgb(E0DBDE)
$color15 = rgb(E7E5E6)
