# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2D2C2C)
$foreground = rgb(FAEDD4)
$color0 = rgb(525151)
$color1 = rgb(232022)
$color2 = rgb(55433E)
$color3 = rgb(584540)
$color4 = rgb(90684A)
$color5 = rgb(81858A)
$color6 = rgb(B59963)
$color7 = rgb(F0DDB9)
$color8 = rgb(A89B82)
$color9 = rgb(2F2B2D)
$color10 = rgb(725953)
$color11 = rgb(765C55)
$color12 = rgb(C08A63)
$color13 = rgb(ACB1B8)
$color14 = rgb(F1CC84)
$color15 = rgb(F0DDB9)
