# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F1F3F5
background         #111516
cursor             #CED7DB

active_tab_foreground     #111516
active_tab_background     #F1F3F5
inactive_tab_foreground   #F1F3F5
inactive_tab_background   #111516

active_border_color   #F1F3F5
inactive_border_color #111516
bell_border_color     #58686F

color0      #262A2B
color1		#58686F
color2		#818C92
color3		#9AA0A4
color4		#A1A6A9
color5		#A1A6A9
color6		#A1A6A9
color7		#E2E6E8
color8		#9FA1A2
color9		#758B94
color10		#ACBBC2
color11		#CED6DA
color12		#D7DDE1
color13		#D7DDE1
color14		#D7DDE1
color15		#E2E6E8
