# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FAEDD4
background         #2D2C2C
cursor             #B6A393

active_tab_foreground     #2D2C2C
active_tab_background     #FAEDD4
inactive_tab_foreground   #FAEDD4
inactive_tab_background   #2D2C2C

active_border_color   #FAEDD4
inactive_border_color #2D2C2C
bell_border_color     #232022

color0      #525151
color1		#232022
color2		#55433E
color3		#584540
color4		#90684A
color5		#81858A
color6		#B59963
color7		#F0DDB9
color8		#A89B82
color9		#2F2B2D
color10		#725953
color11		#765C55
color12		#C08A63
color13		#ACB1B8
color14		#F1CC84
color15		#F0DDB9
