# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F4F2F3
background         #000001
cursor             #949597

active_tab_foreground     #000001
active_tab_background     #F4F2F3
inactive_tab_foreground   #F4F2F3
inactive_tab_background   #000001

active_border_color   #F4F2F3
inactive_border_color #000001
bell_border_color     #27292C

color0      #000001
color1		#27292C
color2		#272A2D
color3		#2B2E31
color4		#676D6F
color5		#676D6F
color6		#A8A4A7
color7		#E7E5E6
color8		#A2A0A1
color9		#34373B
color10		#34373B
color11		#3A3E42
color12		#899194
color13		#899194
color14		#E0DBDE
color15		#E7E5E6
